# frozen_string_literal: true

require 'spec_helper'

describe 'rdbduprunner::autobackup' do
  # let(:facts) do
  #   { 'hostname' => 'example.com' }
  # end
  let(:title) { 'namevar' }
  let(:params) do
    { 'destination' => '/tmp/backup',
      #'host' => 'example.com',
    }
  end
  let(:pre_condition) { 'include rdbduprunner' }

  on_supported_os.each do |os, os_facts|
    context "on #{os}" do
      let(:facts) { os_facts }
      
      it { is_expected.to compile }
      it { is_expected.to contain_concat('/etc/rdbduprunner/conf.d/namevar.conf').
                            with('ensure' => 'present',
                                 'owner' => 'root',
                                 'group' => 0,
                                 'mode' => '0440',
                                ) }
      it { is_expected.to contain_concat__fragment('comment in /etc/rdbduprunner/conf.d/namevar.conf').
                            with('target' => '/etc/rdbduprunner/conf.d/namevar.conf',
                                 'content' =>  "# generated by puppet for foo\n",
                                 'order' => '00') }
      it { is_expected.to contain_concat__fragment('empty line in /etc/rdbduprunner/conf.d/namevar.conf').
                            with('target' => '/etc/rdbduprunner/conf.d/namevar.conf',
                                 'content' =>  "\n",
                                 'order' => '25') }
      it { is_expected.to contain_rdbduprunner__backupdestination('namevar')
                            .with('backup_type' => 'rsync',
                                  'path'        => '/tmp/backup',
                                  'config_file' => '/etc/rdbduprunner/conf.d/namevar.conf',
                                  'concat'      => true,
                                  'inplace'     => nil,
                                  'wholefile'   => false) }
      it { is_expected.to contain_concat__fragment('backupdestination/namevar//etc/rdbduprunner/conf.d/namevar.conf') }
      it { is_expected.to contain_rdbduprunner__backupset('autobackup')
                            .with('host' => 'foo',
                                  'rtag'              => nil,
                                  'disabled'          => nil,
                                  'backupdestination' => 'namevar',
                                  'inventory'         => true,
                                  'inplace'           => nil,
                                  'prerun'            => nil,
                                  'postrun'           => nil,
                                  'paths'             => [],
                                  'skips'             => [ '/var/lib/mysql', '/var/lib/pgsql' ],
                                  'skipres'           => [ '^\/run\/media', '^\/var\/lib\/docker\/devicemapper' ],
                                  'excludes'          => [],
                                 )
      }
      it { is_expected.to contain_concat__fragment('backupset|autobackup|/etc/rdbduprunner/conf.d/namevar.conf') }
      it { is_expected.to contain_file('/root/.rdbduprunner.rc')
                            .with('ensure' => 'link',
                                  'target' => '/etc/rdbduprunner.rc',
                                  'replace' => false,
                                 )
      }
      it { is_expected.to contain_file('/etc/cron.daily/rdbduprunner_autobackup_namevar.sh')
                            .with('ensure' => 'absent')
      }
    end
  end
  context "all options" do
    let(:title) { 'sample' }
    let(:params) do
      { 'destination' => '/tmp/backup',
        'host' => 'example.com',
        'inplace' => false,
        'wholefile' => true,
        'backupdestination' => 'data',
        'rtag' => 'bad-idea',
        'disabled' => false,
        'inventory' => false,
        'prerun' => '/bin/true',
        'postrun' => '/bin/false',
        'paths' => ['/usr/bin'],
        'skips' => ['/test'],
        'skipres' => ['^/test'],
        'excludes' => ['.junk'],
      }
    end
    it { is_expected.to contain_concat('/etc/rdbduprunner/conf.d/sample.conf')
                          .with('ensure' => 'present',
                                'owner' => 'root',
                                'group' => 0,
                                'mode' => '0440',
                               ) }
    it { is_expected.to contain_concat__fragment('comment in /etc/rdbduprunner/conf.d/sample.conf').
                          with('target' => '/etc/rdbduprunner/conf.d/sample.conf',
                               'content' =>  "# generated by puppet for example.com\n",
                               'order' => '00') }
    it { is_expected.to contain_concat__fragment('empty line in /etc/rdbduprunner/conf.d/sample.conf').
                          with('target' => '/etc/rdbduprunner/conf.d/sample.conf',
                               'content' =>  "\n",
                               'order' => '25') }
    it { is_expected.to contain_rdbduprunner__backupdestination('data')
                          .with('backup_type' => 'rsync',
                                'path'        => '/tmp/backup',
                                'config_file' => '/etc/rdbduprunner/conf.d/sample.conf',
                                'concat'      => true,
                                'inplace'     => false,
                                'wholefile'   => true) }
    it { is_expected.to contain_concat__fragment('backupdestination/data//etc/rdbduprunner/conf.d/sample.conf') }
    it { is_expected.to contain_rdbduprunner__backupset('autobackup')
                          .with('host' => 'example.com',
                                'rtag'              => 'bad-idea',
                                'disabled'          => false,
                                'backupdestination' => 'data',
                                'inventory'         => false,
                                'inplace'           => false,
                                'prerun'            => '/bin/true',
                                'postrun'           => '/bin/false',
                                'paths'             => ['/usr/bin'],
                                'skips'             => [ '/test', '/var/lib/mysql', '/var/lib/pgsql' ].sort,
                                'skipres'           => [ '^/test', '^\/run\/media', '^\/var\/lib\/docker\/devicemapper' ].sort,
                                'excludes'          => ['.junk'],
                               )
    }
    it { is_expected.to contain_concat__fragment('backupset|autobackup|/etc/rdbduprunner/conf.d/sample.conf') }
    it { is_expected.to contain_file('/etc/cron.daily/rdbduprunner_autobackup_sample.sh')
                          .with('ensure' => 'absent')
    }
  end
  context "file related options" do
    let(:params) do
      { 'destination' => '/tmp/backup',
        'owner' => 'bob',
        'group' => 'dog',
        'mode' => '0640',
      }
    end
    it { is_expected.to contain_concat('/etc/rdbduprunner/conf.d/namevar.conf').
                          with('ensure' => 'present',
                               'owner' => 'bob',
                               'group' => 'dog',
                               'mode' => '0640',
                              ) }
  end
end
